# Generated by Django 4.1.4 on 2023-01-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="point",
            field=models.IntegerField(default=10000),
        ),
    ]
