# Generated by Django 4.1.4 on 2023-01-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_member_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
