# Generated by Django 4.1.4 on 2023-01-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_member_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="ordid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
