# Generated by Django 4.1.4 on 2023-01-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_history_ordid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="cdate",
            field=models.DateTimeField(),
        ),
    ]
